name: Export C7 Game
on: [workflow_dispatch]
env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: C7

jobs:
  Export-C7-Windows:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
          if [ -f ./c7-static-map-save.json ]; then cp ./c7-static-map-save.json ../build/windows/; fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: C7-Windows
          path: build/windows
  Export-C7-Linux:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
          if [ -f ./c7-static-map-save.json ]; then cp ./c7-static-map-save.json ../build/linux/; fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: C7-Linux-x86_64
          path: build/linux
  Export-C7-Mac:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $EXPORT_NAME
          godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.dmg
          if [ -f ./c7-static-map-save.json ]; then cp ./c7-static-map-save.json ../build/mac/; fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: C7-Mac
          path: build/mac
