name: Export C7 Game
on:
  workflow_dispatch:
    inputs:
      debug-build:
        type: boolean
        description: Checked for debug build, unchecked for release
        default: true
      folder-suffix:
        description: Will be added to $EXPORT_NAME for folder name
        required: false
      include-username:
        type: boolean
        description: Append your GitHub username to the folder name
        default: true
      include-datetime:
        type: boolean
        description: Append ISO8601 date/time to folder name
        default: true
  pull_request:
    branches:
    - 'Development'
    # Add any long-lived branches that need CI here.
  push:
    branches:
    - 'Development'
    # Add any long-lived branches that need CI here.


env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: OpenCiv3
  PROJECT_DIR: C7

jobs:
  Export-C7-Windows:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - uses: ./.github/workflows/composite/buildSetup
    - name: Windows Build
      run: |
        mkdir -v -p build/${FOLDER_NAME}
        cd ${PROJECT_DIR}
        dotnet build
        godot -v --headless --export${BUILD_SUFFIX} "Windows Desktop" ../build/${FOLDER_NAME}/${EXPORT_NAME}.exe
    - name: Run tests
      run: |
        dotnet test C7
    - name: Verify formatting (`run dotnet format C7/C7.sln whitespace` to fix)
      run: |
        dotnet format C7/C7.sln whitespace --verify-no-changes
    - name: Copy Static Files
      run: |
        if cp -r ${PROJECT_DIR}/Text build/${FOLDER_NAME}/Text && \\
           cp -r ${PROJECT_DIR}/Assets build/${FOLDER_NAME}/Assets && \\
           cp -r ${PROJECT_DIR}/Lua build/${FOLDER_NAME}/Lua
        then
          echo "successfully copied static files to build"
        else
          echo "::warning title=Static File Copy Failed::Failed to add the static files to the build"
          exit 1
        fi
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FOLDER_NAME }}-Windows
        path: build/${{ ENV.FOLDER_NAME }}
  Export-C7-Linux:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - uses: ./.github/workflows/composite/buildSetup
    - name: Linux Build
      run: |
        mkdir -v -p build/${FOLDER_NAME}
        cd ${PROJECT_DIR}
        dotnet build
        godot -v --headless --export${BUILD_SUFFIX} "Linux/X11" ../build/${FOLDER_NAME}/${EXPORT_NAME}.x86_64
    - name: Run tests
      run: |
        dotnet test C7
    - name: Verify formatting (`run dotnet format C7/C7.sln whitespace` to fix)
      run: |
        dotnet format C7/C7.sln whitespace --verify-no-changes
    - name: Copy Static Files
      run: |
        if cp -r ${PROJECT_DIR}/Text build/${FOLDER_NAME}/Text && \\
           cp -r ${PROJECT_DIR}/Assets build/${FOLDER_NAME}/Assets && \\
           cp -r ${PROJECT_DIR}/Lua build/${FOLDER_NAME}/Lua
        then
          echo "successfully copied static files to build"
        else
          echo "::warning title=Static File Copy Failed::Failed to add the static files to the build"
          exit 1
        fi
    - name: Create Tar Archive
      run: |
        tar -C build -zcvf build/${FOLDER_NAME}.tgz ${FOLDER_NAME}
    - name: Upload  Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/${{ env.FOLDER_NAME }}.tgz
        name: ${{ env.FOLDER_NAME }}-Linux-x86_64
  Export-C7-Mac:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - uses: ./.github/workflows/composite/buildSetup
    - name: Mac Build
      run: |
        mkdir -v -p build/${FOLDER_NAME}
        cd ${PROJECT_DIR}
        dotnet build
        godot -v --headless --export${BUILD_SUFFIX} "macOS" ../build/${FOLDER_NAME}.zip
    - name: Run tests
      run: |
        dotnet test C7
    - name: Verify formatting (`run dotnet format C7/C7.sln whitespace` to fix)
      run: |
        dotnet format C7/C7.sln whitespace --verify-no-changes
    - name: Copy Static Files
      run: |
        cd ${PROJECT_DIR}
        if zip -r ../build/${FOLDER_NAME}.zip Assets Text Lua
        then
          echo "successfully copied static files to build"
        else
          echo "::warning title=Static File Copy Failed::Failed to add the static files to the build"
          exit 1
        fi
    - name: Upload  Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FOLDER_NAME }}-Mac
        path: build/${{ env.FOLDER_NAME }}.zip
