name: Run C7 Tests

on: [push]

jobs:
  Run-EngineTests:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Run Tests
      run: |
        ./do test
