name: Test Action
on:
  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: This selection does nothing yet
        options:
        - debug
        - release
      folder-suffix:
        description: Will be added to "C7" for folder name
        default: -dev-build
        required: false
      include-username:
        type: boolean
        description: Append your GitHub username to the folder name
        default: true

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: C7
  # Saw this trick using fromJSON and a boolean index to pick whether to include empty string or a value
  DIR_SUFFIX: ${{ inputs.folder-suffix }}${{ fromJSON["'','-'""][ inputs.include-username == 'true' ] }}${{ fromJSON["'',github.actor""][ inputs.include-username == 'true' ] }}

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Make a tar archive
        run: |
          echo "I did a thing"
          echo "Build type is ${{ inputs.build-type }}"
          echo "Folder/file names will be ${EXPORT_NAME}${DIR_SUFFIX}"
