name: Run C7 Tests

on: [push]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: false

    - name: Install Mono
      run: >
        apt-get update -y;
        apt-get install dirmngr gnupg apt-transport-https ca-certificates software-properties-common -y;
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
        apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' -y;
        apt install mono-complete -y;

    - name: Run Tests
      run: |
        ./do test
