name: Run C7 Tests

on: [push]

jobs:
  Run-EngineTests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Run Tests
      run: |
        ./do test
