name: Test Action
on:
  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: This selection does nothing yet
        options:
        - debug
        - release
      folder-suffix:
        description: Will be added to "C7" for folder name
        required: false
      include-username:
        type: boolean
        description: Append your GitHub username to the folder name

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: C7
  DIR_NAME: ${{ env.EXPORT_NAME }}${{ inputs.folder-suffix }}${{ github.actor }}

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Make a tar archive
        run: |
          echo "I did a thing"
          echo "Build type is ${{ inputs.build-type }}"
          echo "Folder/file names will be ${DIR_NAME}"
