name: Test Action
on:
  workflow_dispatch
    inputs:
      name:
        type: choice
        description: This selection does nothing yet, testing inputs
        options:
        - Pan-galactic gargle blaster
        - Tea
      message:
        required: false
      environment:
        type: environment

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Make a tar archive
        run: |
          echo "I did a thing"
