name: Test Action
on:
  workflow_dispatch:
    inputs:
      drink-order:
        type: choice
        description: Drink Order
        options:
        - Pan-Galactic Gargle Blaster
        - Tea

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
    - name: Echo some stuff
      run: |
        echo "I did a thing"
        echo "Here is your ${{ github.event.inputs.drink-order }}"
