name: Test Action
on:
  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: This selection does nothing yet
        options:
        - debug
        - release
      folder-suffix:
        description: Will be added to "C7" for folder name
        default: -dev-build
        required: false
      include-username:
        type: boolean
        description: Append your GitHub username to the folder name
        default: true

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: C7

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
    - name: Optionally set GH_USERNAME
      if: github.event.inputs.include-username
      # ref https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files
      run: echo "GH_USERNAME=-${{ github.actor }}" >> $GITHUB_ENV
    - name: Echo some stuff
      run: |
        echo "I did a thing"
        echo "Build type is ${{ inputs.build-type }}"
        echo "Folder/file names will be ${EXPORT_NAME}${{ github.event.inputs.folder-suffix }}${GH_USERNAME}"
