name: Test Action
on:
  workflow_dispatch:
    inputs:
      drink-order:
        type: choice
        description: Drink Order
        options:
        - Pan-Galactic Gargle Blaster
        - Tea
      must-check:
        type: boolean
        description: Please check this box

jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
    - name: Check if box was checked
      if: github.event.inputs.must-check == 'false'
      run: |
        echo "::warning title=Box not checked::User did not click the box!"
    - name: Echo some stuff
      run: |
        echo "I did a thing"
        echo "Here is your ${{ github.event.inputs.drink-order }}"
